absolute_urls: false
timezone: Europe/Amsterdam
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
force_ssl: true
languages:
  include_default_lang: true
  translations: false
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /home
  hide_in_urls: false
pages:
  theme: djo-amersfoort
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: 'd-m-Y H:i'
    short: 'd-m-y G:i'
    long: 'D, d M Y G:i:s'
  publish_dates: true
  process:
    markdown: true
    twig: false
  twig_first: false
  never_cache_twig: false
  events:
    page: true
    twig: true
  markdown:
    extra: true
    auto_line_breaks: false
    auto_url_links: true
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  expires: 604800
  last_modified: true
  etag: true
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '303'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
      - forms
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
  cli_compatibility: false
  lifetime: 604800
  gzip: true
  allow_webserver_gzip: false
twig:
  cache: true
  debug: false
  auto_reload: false
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: true
  css_pipeline_include_externals: false
  css_pipeline_before_excludes: true
  css_minify: false
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: true
  js_pipeline_include_externals: false
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: true
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: '0'
  log: true
debugger:
  enabled: false
  shutdown:
    close_connection: true
images:
  default_image_quality: 85
  cache_all: true
  cache_perms: '0755'
  debug: false
  auto_fix_orientation: true
media:
  enable_media_timestamp: false
  upload_limit: 0
session:
  enabled: true
  timeout: 1800
  name: djo-grav
  secure: true
  httponly: true
  split: true
gpm:
  releases: stable
  method: curl
  verify_peer: true
