timezone: Europe/Amsterdam
force_ssl: true
languages:
  translations: false
pages:
  theme: djo-amersfoort
  list:
    count: 20
  dateformat:
    default: 'd-m-Y H:i'
    short: 'd-m-y G:i'
    long: 'D, d M Y G:i:s'
  publish_dates: true
  markdown:
    auto_url_links: true
  last_modified: true
  etag: true
  redirect_default_code: '303'
cache:
  enabled: true
  gzip: true
  allow_webserver_gzip: false
twig:
  cache: true
  debug: false
  auto_reload: false
  autoescape: false
  undefined_functions: true
  undefined_filters: true
assets:
  css_pipeline: true
  css_pipeline_include_externals: false
  css_minify: false
  css_rewrite: true
  js_pipeline: true
  js_pipeline_include_externals: false
  js_minify: true
  enable_asset_timestamp: true
errors:
  display: 0
  log: true
debugger:
  enabled: false
images:
  default_image_quality: 85
  cache_all: true
  cache_perms: '0755'
  auto_fix_orientation: true
media:
  enable_media_timestamp: false
  upload_limit: 0
session:
  timeout: 1800
  name: djo-grav
  secure: true
  httponly: true
  split: true
gpm:
  releases: stable
  method: curl
  verify_peer: true

